# syslog-ng deploy
version: '3'
services:

  syslog:
    build:
      context: .
      dockerfile: Dockerfile
    image: networkmgmt/syslog-ng
    ports:
      - 514:514
      - 514:514/udp
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
      - ~/.database/syslog-ng:/var/log/syslog:rw
    restart: always
