# syslog-ng deploy
version: '3'
services:

  syslog:
    build:
      context: ./syslog-ng
      dockerfile: Dockerfile
    image: networkmgmt/syslog-ng
    ports:
      - 514:514
      - 514:514/udp
    volumes:
      - ./syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
      - ~/docker/.database/syslog:/var/log/syslog:rw
    restart: always
